services:
  # Backend API service
  - type: web
    name: kkmk-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_CONNECTION_STRING
        value: postgres://kkmk_db:${DB_PASSWORD}@dpg-cuq5r8ggph6c73cuq6ig-a.singapore-postgres.render.com:5432/kkmk
      - key: FRONTEND_URL
        value: https://kkmk-test.onrender.com

  # Frontend service
  - type: web
    name: kkmk-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: VITE_API_URL
        value: https://kkmk-test-ncal.onrender.com